# Generated by Django 5.2.17 on 2026-08-16 08:59

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import knowledge.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_key', models.CharField(max_length=120)),
                ('time_start_year', models.BigIntegerField()),
                ('time_end_year', models.BigIntegerField()),
                ('topic', models.CharField(default='allgemein', max_length=120)),
                ('language', models.CharField(default='de', max_length=24)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('assertion_count', models.PositiveIntegerField(default=0)),
                ('last_researched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cell_key', 'time_start_year', 'time_end_year', 'topic', 'language'), name='unique_coverage_slice')],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('place', 'Ort'), ('building', 'Bauwerk'), ('person', 'Person'), ('organization', 'Organisation'), ('polity', 'Herrschaftsgebiet'), ('event', 'Ereignis'), ('movement', 'Bewegung'), ('natural_feature', 'Naturraum'), ('other', 'Sonstiges')], default='other', max_length=32)),
                ('canonical_name', models.CharField(max_length=300)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('descriptions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'indexes': [models.Index(fields=['canonical_name'], name='knowledge_e_canonic_e7b3db_idx'), models.Index(fields=['kind'], name='knowledge_e_kind_146151_idx')],
            },
        ),
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicate', models.SlugField(max_length=120)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('time_start_year', models.BigIntegerField(blank=True, null=True)),
                ('time_end_year', models.BigIntegerField(blank=True, help_text='Inklusives Endjahr', null=True)),
                ('time_precision', models.CharField(choices=[('day', 'Tag'), ('month', 'Monat'), ('year', 'Jahr'), ('decade', 'Jahrzehnt'), ('century', 'Jahrhundert'), ('range', 'Zeitraum'), ('unknown', 'Unbekannt')], default='unknown', max_length=16)),
                ('temporal_uncertainty_years', models.PositiveBigIntegerField(default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('spatial_precision_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('candidate', 'Automatisch gefunden'), ('verified', 'Belegt'), ('disputed', 'Widersprüchlich'), ('rejected', 'Verworfen')], default='candidate', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('extraction_method', models.CharField(default='manual', max_length=120)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_assertions', to='knowledge.entity')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='knowledge.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=80)),
                ('external_id', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identifiers', to='knowledge.entity')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
                ('valid_from_year', models.BigIntegerField(blank=True, null=True)),
                ('valid_to_year', models.BigIntegerField(blank=True, null=True)),
                ('spatial_precision_meters', models.PositiveIntegerField(default=100)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('is_reconstruction', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometries', to='knowledge.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('radius_km', models.PositiveIntegerField(default=25)),
                ('time_start_year', models.BigIntegerField()),
                ('time_end_year', models.BigIntegerField()),
                ('topics', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(default=knowledge.models.default_research_languages)),
                ('status', models.CharField(choices=[('queued', 'Vorgemerkt'), ('running', 'Recherche läuft'), ('complete', 'Abgeschlossen'), ('partial', 'Teilweise abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='queued', max_length=16)),
                ('trigger_count', models.PositiveIntegerField(default=1)),
                ('discovered_assertions', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_requested_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'last_requested_at'], name='knowledge_r_status_c9f3ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1200)),
                ('record_id', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(choices=[('primary', 'Primärquelle'), ('scholarly', 'Wissenschaft'), ('institution', 'Institution'), ('encyclopedia', 'Enzyklopädie'), ('community', 'Community'), ('user', 'Benutzerhinweis')], default='encyclopedia', max_length=24)),
                ('language', models.CharField(default='de', max_length=24)),
                ('license_name', models.CharField(blank=True, max_length=200)),
                ('license_url', models.URLField(blank=True, max_length=1200)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'source_type'], name='knowledge_s_provide_dea03c_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'record_id', 'url'), name='unique_source_record')],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('supports', 'stützt'), ('refutes', 'widerspricht'), ('mentions', 'erwähnt')], default='supports', max_length=16)),
                ('locator', models.CharField(blank=True, max_length=500)),
                ('excerpt', models.TextField(blank=True, help_text='Nur kurzer Belegauszug oder Paraphrase')),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='knowledge.assertion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='knowledge.source')),
            ],
        ),
        migrations.AddIndex(
            model_name='assertion',
            index=models.Index(fields=['predicate', 'status'], name='knowledge_a_predica_538377_idx'),
        ),
        migrations.AddIndex(
            model_name='assertion',
            index=models.Index(fields=['time_start_year', 'time_end_year'], name='knowledge_a_time_st_29de3b_idx'),
        ),
        migrations.AddIndex(
            model_name='assertion',
            index=models.Index(fields=['confidence'], name='knowledge_a_confide_8480df_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalidentifier',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_external_identifier'),
        ),
        migrations.AddIndex(
            model_name='placegeometry',
            index=models.Index(fields=['valid_from_year', 'valid_to_year'], name='knowledge_p_valid_f_534e8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('assertion', 'source', 'relation'), name='unique_assertion_evidence'),
        ),
    ]
