# Generated by Django 5.2.17 on 2026-08-16 09:21

import django.contrib.gis.db.models.fields
import django.core.validators
import knowledge.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorationContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_name', models.CharField(default='Krempe', max_length=300)),
                ('center', django.contrib.gis.db.models.fields.PointField(default=knowledge.models.default_exploration_center, geography=True, srid=4326)),
                ('map_zoom', models.DecimalField(decimal_places=1, default=11, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('time_focus_year', models.BigIntegerField(default=1814)),
                ('time_window_years', models.PositiveBigIntegerField(default=10)),
                ('radius_km', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('query', models.CharField(blank=True, max_length=500)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('perspectives', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(default=knowledge.models.default_research_languages)),
                ('include_candidates', models.BooleanField(default=True)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='knowledge_e_updated_ca56cc_idx'), models.Index(fields=['time_focus_year'], name='knowledge_e_time_fo_2234b2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('radius_km__gte', 1), ('radius_km__lte', 1000)), name='context_radius_range'), models.CheckConstraint(condition=models.Q(('map_zoom__gte', 1), ('map_zoom__lte', 20)), name='context_zoom_range'), models.CheckConstraint(condition=models.Q(('time_window_years__lte', 1000000000)), name='context_time_window_range')],
            },
        ),
    ]
