# Generated by Django 5.2.17 on 2026-08-16 09:25

from django.db import migrations, models


def normalize_initial_contexts(apps, schema_editor):
    exploration_context = apps.get_model("knowledge", "ExplorationContext")
    exploration_context.objects.filter(time_window_years=10).update(time_window_years=0)


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_explorationcontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorationcontext',
            name='time_window_years',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.RunPython(normalize_initial_contexts, migrations.RunPython.noop),
    ]
