# Generated by Django 5.2.17 on 2026-08-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_explorationcontext_time_window_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorationcontext',
            name='query_mode',
            field=models.CharField(choices=[('auto', 'Automatisch erkennen'), ('place', 'Ort'), ('topic', 'Thema')], default='auto', max_length=16),
        ),
    ]
