# Generated by Django 5.2.17 on 2026-08-16 13:03

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_explorationcontext_event_anchor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('provider', models.CharField(max_length=200)),
                ('data_kind', models.CharField(choices=[('vector', 'Vektordaten'), ('raster', 'Rasterdaten'), ('station', 'Stationsdaten'), ('reconstruction', 'Rekonstruktion'), ('document', 'Dokumentarische Beobachtung')], max_length=24)),
                ('storage_kind', models.CharField(choices=[('external', 'Externe Quelle'), ('object', 'Objektspeicher'), ('database', 'Datenbankausschnitt')], default='external', max_length=24)),
                ('asset_uri', models.CharField(blank=True, max_length=1600)),
                ('file_format', models.CharField(blank=True, max_length=80)),
                ('variable_name', models.CharField(blank=True, max_length=160)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('spatial_coverage', django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326)),
                ('spatial_resolution_meters', models.PositiveBigIntegerField(blank=True, null=True)),
                ('spatial_resolution_text', models.CharField(blank=True, max_length=200)),
                ('time_start_year', models.BigIntegerField(blank=True, null=True)),
                ('time_end_year', models.BigIntegerField(blank=True, null=True)),
                ('reference_period_start_year', models.BigIntegerField(blank=True, null=True)),
                ('reference_period_end_year', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environmental_datasets', to='knowledge.source')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=300)),
                ('event_type', models.CharField(choices=[('volcano', 'Vulkanausbruch'), ('storm_surge', 'Sturmflut'), ('drought', 'Dürre'), ('heatwave', 'Hitzewelle'), ('frost', 'Frost / Kälteperiode'), ('flood', 'Hochwasser'), ('other', 'Anderes Naturereignis')], max_length=24)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326)),
                ('spatial_resolution_meters', models.PositiveBigIntegerField(blank=True, null=True)),
                ('time_start_year', models.BigIntegerField()),
                ('time_end_year', models.BigIntegerField()),
                ('time_precision', models.CharField(choices=[('day', 'Tag'), ('month', 'Monat'), ('year', 'Jahr'), ('decade', 'Jahrzehnt'), ('century', 'Jahrhundert'), ('range', 'Zeitraum'), ('unknown', 'Unbekannt')], default='year', max_length=16)),
                ('temporal_uncertainty_years', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('candidate', 'Automatisch gefunden'), ('verified', 'Belegt'), ('disputed', 'Widersprüchlich'), ('rejected', 'Verworfen')], default='candidate', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='knowledge.environmentaldataset')),
                ('evidence', models.ManyToManyField(blank=True, related_name='environmental_events', to='knowledge.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=300)),
                ('method', models.CharField(choices=[('measurement', 'Messung'), ('reconstruction', 'Rekonstruktion'), ('documentary', 'Dokumentarische Beobachtung')], max_length=24)),
                ('variable', models.CharField(max_length=160)),
                ('value', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('value_min', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('value_max', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326)),
                ('spatial_scope', models.CharField(choices=[('local', 'Lokal'), ('regional', 'Regional'), ('hemispheric', 'Hemisphärisch'), ('global', 'Global')], default='local', max_length=24)),
                ('spatial_resolution_meters', models.PositiveBigIntegerField(blank=True, null=True)),
                ('time_start_year', models.BigIntegerField()),
                ('time_end_year', models.BigIntegerField()),
                ('time_precision', models.CharField(choices=[('day', 'Tag'), ('month', 'Monat'), ('year', 'Jahr'), ('decade', 'Jahrzehnt'), ('century', 'Jahrhundert'), ('range', 'Zeitraum'), ('unknown', 'Unbekannt')], default='year', max_length=16)),
                ('temporal_uncertainty_years', models.PositiveBigIntegerField(default=0)),
                ('reference_period_start_year', models.BigIntegerField(blank=True, null=True)),
                ('reference_period_end_year', models.BigIntegerField(blank=True, null=True)),
                ('aggregation', models.CharField(blank=True, max_length=120)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('candidate', 'Automatisch gefunden'), ('verified', 'Belegt'), ('disputed', 'Widersprüchlich'), ('rejected', 'Verworfen')], default='candidate', max_length=16)),
                ('asset_uri', models.CharField(blank=True, max_length=1600)),
                ('asset_window', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='knowledge.environmentaldataset')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='knowledge.environmentalevent')),
                ('evidence', models.ManyToManyField(blank=True, related_name='environmental_observations', to='knowledge.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('documented', 'Dokumentierte Auswirkung'), ('possible', 'Möglicher Beitrag'), ('coincidence', 'Zeitliche Koinzidenz'), ('disputed', 'Umstrittener Zusammenhang')], default='possible', max_length=24)),
                ('summary', models.TextField()),
                ('mechanism', models.TextField(blank=True)),
                ('temporal_lag_years', models.IntegerField(default=0)),
                ('temporal_confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('spatial_confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('confidence', models.DecimalField(decimal_places=3, default=0.5, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('candidate', 'Automatisch gefunden'), ('verified', 'Belegt'), ('disputed', 'Widersprüchlich'), ('rejected', 'Verworfen')], default='candidate', max_length=16)),
                ('uncertainty_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environmental_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_relations', to='knowledge.environmentalevent')),
                ('evidence', models.ManyToManyField(blank=True, related_name='environmental_relations', to='knowledge.evidence')),
                ('historical_assertion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_relations', to='knowledge.assertion')),
            ],
        ),
        migrations.AddIndex(
            model_name='environmentaldataset',
            index=models.Index(fields=['provider', 'data_kind'], name='knowledge_e_provide_3609da_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentaldataset',
            index=models.Index(fields=['time_start_year', 'time_end_year'], name='knowledge_e_time_st_21c429_idx'),
        ),
        migrations.AddConstraint(
            model_name='environmentaldataset',
            constraint=models.CheckConstraint(condition=models.Q(('time_start_year__isnull', True), ('time_end_year__isnull', True), ('time_start_year__lte', models.F('time_end_year')), _connector='OR'), name='environmental_dataset_time_order'),
        ),
        migrations.AddIndex(
            model_name='environmentalevent',
            index=models.Index(fields=['event_type', 'status'], name='knowledge_e_event_t_9ccda7_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalevent',
            index=models.Index(fields=['time_start_year', 'time_end_year'], name='knowledge_e_time_st_b5e765_idx'),
        ),
        migrations.AddConstraint(
            model_name='environmentalevent',
            constraint=models.CheckConstraint(condition=models.Q(('time_start_year__lte', models.F('time_end_year'))), name='environmental_event_time_order'),
        ),
        migrations.AddConstraint(
            model_name='environmentalevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('dataset', 'external_id'), name='unique_environmental_event_external_id'),
        ),
        migrations.AddIndex(
            model_name='environmentalobservation',
            index=models.Index(fields=['variable', 'method'], name='knowledge_e_variabl_b54167_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalobservation',
            index=models.Index(fields=['time_start_year', 'time_end_year'], name='knowledge_e_time_st_2107ec_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalobservation',
            index=models.Index(fields=['spatial_scope'], name='knowledge_e_spatial_3bbaad_idx'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('time_start_year__lte', models.F('time_end_year'))), name='environmental_observation_time_order'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.CheckConstraint(condition=models.Q(('reference_period_start_year__isnull', True), ('reference_period_end_year__isnull', True), ('reference_period_start_year__lte', models.F('reference_period_end_year')), _connector='OR'), name='environmental_observation_reference_order'),
        ),
        migrations.AddConstraint(
            model_name='environmentalobservation',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('dataset', 'external_id'), name='unique_environmental_observation_external_id'),
        ),
        migrations.AddIndex(
            model_name='environmentalrelation',
            index=models.Index(fields=['relation_type', 'status'], name='knowledge_e_relatio_036426_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalrelation',
            index=models.Index(fields=['confidence'], name='knowledge_e_confide_92d08d_idx'),
        ),
        migrations.AddConstraint(
            model_name='environmentalrelation',
            constraint=models.UniqueConstraint(fields=('environmental_event', 'historical_assertion', 'relation_type'), name='unique_environmental_historical_relation'),
        ),
    ]
