# Generated by Django 5.2.17 on 2026-08-18 08:09

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import knowledge.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0013_environmental_place_search_and_tsunami"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("place", "Ort"),
                    ("building", "Bauwerk"),
                    ("person", "Person"),
                    ("organization", "Organisation"),
                    ("polity", "Herrschaftsgebiet"),
                    ("event", "Ereignis"),
                    ("movement", "Bewegung"),
                    ("process", "Historischer Prozess"),
                    ("natural_feature", "Naturraum"),
                    ("other", "Sonstiges"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("intellectual", "Ideen- und Wissensgeschichte"),
                            ("political", "Politischer Prozess"),
                            ("social", "Gesellschaftlicher Prozess"),
                            ("economic", "Wirtschaftlicher Prozess"),
                            ("religious", "Religiöser Prozess"),
                            ("cultural", "Kultureller Prozess"),
                            ("environmental", "Umwelt- und Klimaprozess"),
                            ("technological", "Technischer Prozess"),
                            ("demographic", "Demografischer Prozess"),
                            ("other", "Sonstiger Prozess"),
                        ],
                        max_length=24,
                    ),
                ),
                ("summary", models.TextField()),
                ("time_start_year", models.BigIntegerField(blank=True, null=True)),
                ("time_end_year", models.BigIntegerField(blank=True, null=True)),
                (
                    "time_precision",
                    models.CharField(
                        choices=[
                            ("day", "Tag"),
                            ("month", "Monat"),
                            ("year", "Jahr"),
                            ("decade", "Jahrzehnt"),
                            ("century", "Jahrhundert"),
                            ("range", "Zeitraum"),
                            ("unknown", "Unbekannt"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("temporal_uncertainty_years", models.PositiveBigIntegerField(default=0)),
                (
                    "temporal_scope",
                    models.CharField(
                        choices=[
                            ("bounded", "Begrenzter Zeitraum"),
                            ("open_start", "Offener Beginn"),
                            ("open_end", "Offenes Ende"),
                            ("timeless", "Zeitunabhängig"),
                            ("unknown", "Zeit unbekannt"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "spatial_extent",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "spatial_scope",
                    models.CharField(
                        choices=[
                            ("point", "Punkt"),
                            ("feature", "Räumliches Objekt"),
                            ("region", "Region"),
                            ("global", "Global"),
                            ("unknown", "Raumbezug unbekannt"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("spatial_precision_meters", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Automatisch gefunden"),
                            ("verified", "Belegt"),
                            ("disputed", "Widersprüchlich"),
                            ("rejected", "Verworfen"),
                        ],
                        default="candidate",
                        max_length=16,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        default=0.5,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "confidence_reason",
                    models.TextField(default=knowledge.models.default_confidence_reason),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "defining_assertions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Aussagen, die Existenz, Zeitraum oder Raumbezug des Prozesses stützen.",
                        related_name="defined_processes",
                        to="knowledge.assertion",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_process",
                        to="knowledge.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessAssertionRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("manifests_in", "Manifestiert sich in"),
                            ("material_trace", "Hinterlässt materielle Spur"),
                            ("institutionalized_by", "Wird institutionalisiert durch"),
                            ("legitimized_by", "Wird legitimiert durch"),
                            ("spreads_through", "Verbreitet sich durch"),
                            ("influences", "Beeinflusst"),
                            ("contributes_to", "Trägt bei zu"),
                            ("reaction_to", "Ist Reaktion auf"),
                            ("opposes", "Steht im Gegensatz zu"),
                            ("part_of", "Ist Teil von"),
                            ("similar_to", "Ähnelt"),
                            ("contemporary_with", "Ist gleichzeitig mit"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "evidence_level",
                    models.CharField(
                        choices=[
                            ("documented", "Belegter Zusammenhang"),
                            ("scholarly_plausible", "Wissenschaftlich plausible Einordnung"),
                            ("algorithmic_similarity", "Automatisch erkannte Ähnlichkeit"),
                            ("coincidence", "Bloße Gleichzeitigkeit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("summary", models.TextField()),
                ("mechanism", models.TextField(blank=True)),
                ("time_start_year", models.BigIntegerField(blank=True, null=True)),
                ("time_end_year", models.BigIntegerField(blank=True, null=True)),
                ("temporal_uncertainty_years", models.PositiveBigIntegerField(default=0)),
                (
                    "spatial_extent",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                    ),
                ),
                ("spatial_precision_meters", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("confidence_reason", models.TextField()),
                ("extraction_method", models.CharField(default="manual", max_length=120)),
                ("algorithm_name", models.CharField(blank=True, max_length=160)),
                ("algorithm_version", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Automatisch gefunden"),
                            ("verified", "Belegt"),
                            ("disputed", "Widersprüchlich"),
                            ("rejected", "Verworfen"),
                        ],
                        default="candidate",
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assertion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_relations",
                        to="knowledge.assertion",
                    ),
                ),
                (
                    "evidence",
                    models.ManyToManyField(
                        blank=True,
                        related_name="process_assertion_relations",
                        to="knowledge.evidence",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assertion_relations",
                        to="knowledge.historicalprocess",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="historicalprocess",
            index=models.Index(
                fields=["process_type", "status"],
                name="knowledge_h_process_05077a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historicalprocess",
            index=models.Index(
                fields=["time_start_year", "time_end_year"],
                name="knowledge_h_time_st_dc9729_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historicalprocess",
            index=models.Index(
                fields=["spatial_scope", "confidence"],
                name="knowledge_h_spatial_1bc1c0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(("summary", ""), _negated=True),
                name="historical_process_summary_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence_reason", ""), _negated=True),
                name="historical_process_confidence_reason_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalprocess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("time_start_year__isnull", True),
                    ("time_end_year__isnull", True),
                    ("time_start_year__lte", models.F("time_end_year")),
                    _connector="OR",
                ),
                name="historical_process_time_order",
            ),
        ),
        migrations.AddIndex(
            model_name="processassertionrelation",
            index=models.Index(
                fields=["relation_type", "evidence_level"],
                name="knowledge_p_relatio_0f9d9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processassertionrelation",
            index=models.Index(
                fields=["status", "confidence"],
                name="knowledge_p_status_c09db2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="processassertionrelation",
            index=models.Index(
                fields=["time_start_year", "time_end_year"],
                name="knowledge_p_time_st_564d05_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="processassertionrelation",
            constraint=models.UniqueConstraint(
                fields=("process", "assertion", "relation_type", "evidence_level"),
                name="unique_process_assertion_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="processassertionrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("summary", ""), _negated=True),
                name="process_relation_summary_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="processassertionrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence_reason", ""), _negated=True),
                name="process_relation_confidence_reason_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="processassertionrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("time_start_year__isnull", True),
                    ("time_end_year__isnull", True),
                    ("time_start_year__lte", models.F("time_end_year")),
                    _connector="OR",
                ),
                name="process_relation_time_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="processassertionrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("evidence_level", "coincidence"), _negated=True),
                    ("relation_type", "contemporary_with"),
                    _connector="OR",
                ),
                name="process_coincidence_is_only_contemporary",
            ),
        ),
        migrations.AddConstraint(
            model_name="processassertionrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("evidence_level", "algorithmic_similarity"), _negated=True),
                    ("relation_type", "similar_to"),
                    _connector="OR",
                ),
                name="process_algorithmic_similarity_type",
            ),
        ),
    ]
